janus:
  image: "janusgraph/janusgraph"
  hostname: "janus-graph-container"
  ports:
          - "8182:8182"
cassandra:
  image: "cassandra:3.11"
  hostname: "cassandra-container"
  environment:
          CASSANDRA_START_RPC: "true"
  ports:
          - "9160:9160"
          - "9042:9042"
          - "7199:7199"
          - "7000:7000"
          - "7001:7001"
